/**
 * Jeu de départ : 40 cartes originales (aucun meme réel, aucune personne réelle).
 * Source unique : la migration SQL des cartes est générée depuis ce fichier
 * (npm run cards:sql). Les statistiques respectent le budget de chaque rareté (testé).
 */
import type { Card } from "@/lib/validation/card";

export const STARTER_SET: readonly Card[] = [
  {"id": "a1e3a18f-ace1-5a75-94de-4b3436632e71", "slug": "lundi-matin", "name": "Lundi Matin", "rarity": "commune", "vibe": "rage", "description": "Il arrive chaque semaine. Personne ne l'a invité.", "hp": 90, "atk": 40, "def": 35, "spd": 80, "normalAttack": {"name": "Soupir lourd", "power": 28}, "specialAttack": {"name": "Réveil brutal", "power": 55, "energyCost": 2, "effect": {"kind": "debuff", "stat": "spd", "stages": 1}}, "defenseAbility": {"name": "Café serré", "effect": {"kind": "heal", "percent": 10}}, "artSeed": 1234340465, "imageUrl": null},
  {"id": "b0286eaa-cbf5-5779-9f30-92d7579e9d6f", "slug": "wifi-une-barre", "name": "Le Wi-Fi à Une Barre", "rarity": "commune", "vibe": "rage", "description": "Charge depuis 2014. Toujours à 99 %.", "hp": 80, "atk": 38, "def": 32, "spd": 100, "normalAttack": {"name": "Chargement infini", "power": 28}, "specialAttack": {"name": "Déconnexion surprise", "power": 55, "energyCost": 2, "effect": {"kind": "stun", "chance": 20}}, "defenseAbility": {"name": "Redémarrer la box", "effect": {"kind": "recharge", "amount": 1}}, "artSeed": 43662703, "imageUrl": null},
  {"id": "3080b5fa-02b7-56ab-afaf-0eb1cdacc30a", "slug": "chaussette-orpheline", "name": "Chaussette Orpheline", "rarity": "commune", "vibe": "absurde", "description": "Sa jumelle est partie dans la machine. Elle attend.", "hp": 90, "atk": 40, "def": 35, "spd": 80, "normalAttack": {"name": "Coup de pied mou", "power": 28}, "specialAttack": {"name": "Cycle essorage", "power": 55, "energyCost": 2, "effect": {"kind": "multi", "hits": 2, "percent": 40}}, "defenseAbility": {"name": "Boule au fond du tiroir", "effect": {"kind": "dodge", "chance": 15}}, "artSeed": 693966602, "imageUrl": null},
  {"id": "aad410ee-58bc-594d-965f-65c0387f14bf", "slug": "notification-fantome", "name": "Notification Fantôme", "rarity": "commune", "vibe": "chaos", "description": "Ton téléphone a vibré. Ou pas.", "hp": 80, "atk": 38, "def": 32, "spd": 100, "normalAttack": {"name": "Vibration", "power": 28}, "specialAttack": {"name": "Pastille rouge", "power": 55, "energyCost": 2, "effect": {"kind": "debuff", "stat": "def", "stages": 1}}, "defenseAbility": {"name": "Mode avion", "effect": {"kind": "dodge", "chance": 20}}, "artSeed": 351663295, "imageUrl": null},
  {"id": "3a824c2d-452d-59de-8cf6-d79f9c36b336", "slug": "chaton-gene", "name": "Le Chaton Gêné", "rarity": "commune", "vibe": "cringe", "description": "A raté son saut. Fait comme si c'était voulu.", "hp": 90, "atk": 40, "def": 35, "spd": 80, "normalAttack": {"name": "Regard fuyant", "power": 28}, "specialAttack": {"name": "Saut raté", "power": 55, "energyCost": 2, "effect": {"kind": "dot", "percent": 6, "turns": 2}}, "defenseAbility": {"name": "Toilettage nerveux", "effect": {"kind": "cleanse"}}, "artSeed": 551583542, "imageUrl": null},
  {"id": "32b2b46f-0358-5519-8775-cafbff8c2291", "slug": "tata-barbecue", "name": "Tata au Barbecue", "rarity": "commune", "vibe": "wholesome", "description": "Te demande si tu as un amoureux. Devant tout le monde.", "hp": 108, "atk": 34, "def": 43, "spd": 58, "normalAttack": {"name": "Bisou baveux", "power": 28}, "specialAttack": {"name": "Assiette bien remplie", "power": 55, "energyCost": 2, "effect": {"kind": "drain", "percent": 30}}, "defenseAbility": {"name": "Câlin forcé", "effect": {"kind": "heal", "percent": 12}}, "artSeed": 427211409, "imageUrl": null},
  {"id": "c25bcc5e-5407-5b8a-a784-1e1c993204b9", "slug": "pouce-bleu-passif", "name": "Le Pouce Bleu Passif", "rarity": "commune", "vibe": "ironique", "description": "Répond à ton long message par 👍.", "hp": 84, "atk": 50, "def": 29, "spd": 78, "normalAttack": {"name": "Réaction sèche", "power": 28}, "specialAttack": {"name": "Vu à 23 h 58", "power": 55, "energyCost": 2, "effect": {"kind": "debuff", "stat": "atk", "stages": 1}}, "defenseAbility": {"name": "Lu, pas répondu", "effect": {"kind": "reflect", "percent": 20}}, "artSeed": 914558137, "imageUrl": null},
  {"id": "66236bf0-0775-5c9c-8b22-b66bd5f8a3de", "slug": "reunion-mail", "name": "Réunion Qui Aurait Pu Être un Mail", "rarity": "commune", "vibe": "ironique", "description": "Une heure pour dire « on en reparle ».", "hp": 108, "atk": 34, "def": 43, "spd": 58, "normalAttack": {"name": "Tour de table", "power": 28}, "specialAttack": {"name": "Point d'étape", "power": 55, "energyCost": 2, "effect": {"kind": "stun", "chance": 15}}, "defenseAbility": {"name": "Caméra coupée", "effect": {"kind": "dodge", "chance": 15}}, "artSeed": 1865079774, "imageUrl": null},
  {"id": "7ab207af-e790-5350-b3c6-76ed7cde3caa", "slug": "micro-ondes-rebelle", "name": "Le Micro-Ondes Rebelle", "rarity": "commune", "vibe": "chaos", "description": "Bip. Bip. Bip. Le plat est encore gelé au milieu.", "hp": 84, "atk": 50, "def": 29, "spd": 78, "normalAttack": {"name": "Bip strident", "power": 28}, "specialAttack": {"name": "Plat brûlant", "power": 55, "energyCost": 2, "effect": {"kind": "dot", "percent": 7, "turns": 2}}, "defenseAbility": {"name": "Porte entrouverte", "effect": {"kind": "reflect", "percent": 15}}, "artSeed": 204582058, "imageUrl": null},
  {"id": "a919d5c9-6abe-5d83-9e5c-94ed33e802c3", "slug": "calin-de-groupe", "name": "Câlin de Groupe", "rarity": "commune", "vibe": "wholesome", "description": "Personne n'a su comment en sortir.", "hp": 108, "atk": 34, "def": 43, "spd": 58, "normalAttack": {"name": "Accolade", "power": 28}, "specialAttack": {"name": "Tout le monde s'y met", "power": 55, "energyCost": 2, "effect": {"kind": "multi", "hits": 3, "percent": 30}}, "defenseAbility": {"name": "Cercle protecteur", "effect": {"kind": "heal", "percent": 10}}, "artSeed": 1792772803, "imageUrl": null},
  {"id": "33ffbcec-323a-584e-88f6-76cbdbd093ba", "slug": "selfie-rate", "name": "Le Selfie Raté", "rarity": "commune", "vibe": "cringe", "description": "Double menton, flash, yeux fermés. Posté quand même.", "hp": 80, "atk": 38, "def": 32, "spd": 100, "normalAttack": {"name": "Flash aveuglant", "power": 28}, "specialAttack": {"name": "Publication sans filtre", "power": 55, "energyCost": 2, "effect": {"kind": "debuff", "stat": "spd", "stages": 1}}, "defenseAbility": {"name": "Supprimer vite", "effect": {"kind": "dodge", "chance": 20}}, "artSeed": 1725929402, "imageUrl": null},
  {"id": "ab32e2bc-c2f7-522c-9f1b-540f9abefdb5", "slug": "plante-verte-survivante", "name": "Plante Verte Survivante", "rarity": "commune", "vibe": "wholesome", "description": "Arrosée deux fois par an. Elle tient bon.", "hp": 108, "atk": 34, "def": 43, "spd": 58, "normalAttack": {"name": "Feuille fouettante", "power": 28}, "specialAttack": {"name": "Photosynthèse", "power": 55, "energyCost": 2, "effect": {"kind": "buff", "stat": "def", "stages": 1}}, "defenseAbility": {"name": "Racines profondes", "effect": {"kind": "heal", "percent": 12}}, "artSeed": 740154805, "imageUrl": null},
  {"id": "6c1e70da-2287-5cf6-8bfe-25d6d249dc3c", "slug": "mamie-wifi", "name": "Mamie Wi-Fi", "rarity": "rare", "vibe": "wholesome", "description": "Transfère chaque message à toute la famille, avec trois cœurs.", "hp": 96, "atk": 42, "def": 38, "spd": 80, "normalAttack": {"name": "Bisou sonore", "power": 30}, "specialAttack": {"name": "Partage en chaîne", "power": 60, "energyCost": 3, "effect": {"kind": "multi", "hits": 2, "percent": 40}}, "defenseAbility": {"name": "Câlin réseau", "effect": {"kind": "heal", "percent": 12}}, "artSeed": 1954046012, "imageUrl": null},
  {"id": "075cbec5-f233-59b3-b757-c4109fcab8a5", "slug": "le-stagiaire-en-pls", "name": "Le Stagiaire en PLS", "rarity": "rare", "vibe": "cringe", "description": "A cliqué sur « Répondre à tous ». Deux fois.", "hp": 96, "atk": 40, "def": 40, "spd": 80, "normalAttack": {"name": "Réponse à tous", "power": 29}, "specialAttack": {"name": "Mail de 3 h du matin", "power": 70, "energyCost": 3, "effect": {"kind": "dot", "percent": 8, "turns": 2}}, "defenseAbility": {"name": "Excuses en boucle", "effect": {"kind": "cleanse"}}, "artSeed": 1488031909, "imageUrl": null},
  {"id": "b01a2207-da09-5c2e-8a49-34e81d9f6a1c", "slug": "canard-perplexe", "name": "Le Canard Perplexe", "rarity": "rare", "vibe": "absurde", "description": "Ne comprend pas la question. Ni la réponse.", "hp": 94, "atk": 42, "def": 37, "spd": 84, "normalAttack": {"name": "Coin interrogatif", "power": 29}, "specialAttack": {"name": "Pourquoi ?", "power": 60, "energyCost": 3, "effect": {"kind": "stun", "chance": 25}}, "defenseAbility": {"name": "Plonger la tête", "effect": {"kind": "dodge", "chance": 20}}, "artSeed": 1893381660, "imageUrl": null},
  {"id": "70e53eb0-d22b-5610-bc8a-256f7c2be8b4", "slug": "clavier-en-rage", "name": "Clavier en Rage", "rarity": "rare", "vibe": "rage", "description": "ÉCRIT TOUT EN MAJUSCULES. TOUJOURS.", "hp": 88, "atk": 52, "def": 30, "spd": 84, "normalAttack": {"name": "Touche Entrée", "power": 29}, "specialAttack": {"name": "Pavé de colère", "power": 60, "energyCost": 3, "effect": {"kind": "pierce", "percent": 30}}, "defenseAbility": {"name": "Verr. Maj", "effect": {"kind": "reflect", "percent": 25}}, "artSeed": 333950132, "imageUrl": null},
  {"id": "7f218584-f866-5cb4-a52f-6989d8758f3b", "slug": "voisin-perceuse", "name": "Le Voisin Perceuse", "rarity": "rare", "vibe": "rage", "description": "Dimanche, 8 h. Il a des étagères à poser.", "hp": 114, "atk": 35, "def": 45, "spd": 62, "normalAttack": {"name": "Vrille", "power": 29}, "specialAttack": {"name": "Travaux du dimanche", "power": 60, "energyCost": 3, "effect": {"kind": "dot", "percent": 8, "turns": 2}}, "defenseAbility": {"name": "Casque antibruit", "effect": {"kind": "cleanse"}}, "artSeed": 261720891, "imageUrl": null},
  {"id": "595cf39c-f89b-5f3e-92dc-4e4d981134ce", "slug": "sourire-commercial", "name": "Sourire Commercial", "rarity": "rare", "vibe": "ironique", "description": "« Super question ! » Il n'a pas écouté.", "hp": 84, "atk": 40, "def": 36, "spd": 100, "normalAttack": {"name": "Clin d'œil", "power": 29}, "specialAttack": {"name": "Offre exceptionnelle", "power": 60, "energyCost": 3, "effect": {"kind": "debuff", "stat": "atk", "stages": 1}}, "defenseAbility": {"name": "Politesse de façade", "effect": {"kind": "reflect", "percent": 20}}, "artSeed": 1854866638, "imageUrl": null},
  {"id": "15688a44-b475-57f1-a9fb-89745f6c9353", "slug": "dauphin-trottinette", "name": "Dauphin en Trottinette", "rarity": "rare", "vibe": "absurde", "description": "Personne ne sait comment il tient dessus.", "hp": 84, "atk": 40, "def": 36, "spd": 100, "normalAttack": {"name": "Dérapage", "power": 29}, "specialAttack": {"name": "Saut de la vague", "power": 60, "energyCost": 3, "effect": {"kind": "multi", "hits": 2, "percent": 40}}, "defenseAbility": {"name": "Virage serré", "effect": {"kind": "dodge", "chance": 25}}, "artSeed": 1303321427, "imageUrl": null},
  {"id": "cb834da9-9214-5736-978e-7dbfa47447d7", "slug": "chat-ninja-rate", "name": "Chat Ninja Raté", "rarity": "rare", "vibe": "chaos", "description": "Silencieux comme une casserole qui tombe.", "hp": 88, "atk": 52, "def": 30, "spd": 84, "normalAttack": {"name": "Griffe sournoise", "power": 29}, "specialAttack": {"name": "Attaque surprise ratée", "power": 60, "energyCost": 3, "effect": {"kind": "stun", "chance": 25}}, "defenseAbility": {"name": "Disparition (presque)", "effect": {"kind": "dodge", "chance": 20}}, "artSeed": 547289047, "imageUrl": null},
  {"id": "0e980dc1-12ac-53d5-b207-0d502f751528", "slug": "danse-du-mariage", "name": "Danse Gênante du Mariage", "rarity": "rare", "vibe": "cringe", "description": "Tonton s'est lancé sur la piste. Tout le monde filme.", "hp": 94, "atk": 42, "def": 37, "spd": 84, "normalAttack": {"name": "Pas de côté", "power": 29}, "specialAttack": {"name": "Chorégraphie improvisée", "power": 60, "energyCost": 3, "effect": {"kind": "debuff", "stat": "def", "stages": 1}}, "defenseAbility": {"name": "Rire nerveux", "effect": {"kind": "heal", "percent": 10}}, "artSeed": 1631058216, "imageUrl": null},
  {"id": "83b7db9e-ed65-548e-8aeb-cb89357e077f", "slug": "golden-retriever-positif", "name": "Le Golden Retriever Positif", "rarity": "rare", "vibe": "wholesome", "description": "Content de te voir. Content de tout, en fait.", "hp": 94, "atk": 42, "def": 37, "spd": 84, "normalAttack": {"name": "Queue joyeuse", "power": 29}, "specialAttack": {"name": "Léchouille réconfortante", "power": 60, "energyCost": 3, "effect": {"kind": "drain", "percent": 40}}, "defenseAbility": {"name": "Regard tout doux", "effect": {"kind": "heal", "percent": 14}}, "artSeed": 1250390911, "imageUrl": null},
  {"id": "b5b032a0-f3bd-5748-984c-ec4a67934b06", "slug": "le-pigeon-philosophe", "name": "Le Pigeon Philosophe", "rarity": "epique", "vibe": "absurde", "description": "A lu un seul livre. L'a mangé.", "hp": 100, "atk": 46, "def": 36, "spd": 88, "normalAttack": {"name": "Coup de bec pensif", "power": 30}, "specialAttack": {"name": "Et si tout était miettes", "power": 65, "energyCost": 3, "effect": {"kind": "stun", "chance": 25}}, "defenseAbility": {"name": "Envol pensif", "effect": {"kind": "dodge", "chance": 20}}, "artSeed": 948528902, "imageUrl": null},
  {"id": "5a350aeb-1295-5035-831e-4c8102341b73", "slug": "le-grand-malaise", "name": "Le Grand Malaise", "rarity": "epique", "vibe": "cringe", "description": "Le silence qui suit une blague ratée. En personne.", "hp": 120, "atk": 37, "def": 48, "spd": 62, "normalAttack": {"name": "Silence pesant", "power": 30}, "specialAttack": {"name": "Blague tombée à plat", "power": 65, "energyCost": 3, "effect": {"kind": "dot", "percent": 10, "turns": 2}}, "defenseAbility": {"name": "Changer de sujet", "effect": {"kind": "cleanse"}}, "artSeed": 1562817395, "imageUrl": null},
  {"id": "1575707f-7c5e-5bcc-bb56-90cc69b6bbf7", "slug": "tornade-notifications", "name": "Tornade de Notifications", "rarity": "epique", "vibe": "chaos", "description": "147 messages non lus dans le groupe de la famille.", "hp": 88, "atk": 42, "def": 40, "spd": 100, "normalAttack": {"name": "Ding", "power": 30}, "specialAttack": {"name": "Avalanche de messages", "power": 65, "energyCost": 3, "effect": {"kind": "multi", "hits": 3, "percent": 35}}, "defenseAbility": {"name": "Ne pas déranger", "effect": {"kind": "dodge", "chance": 25}}, "artSeed": 100873207, "imageUrl": null},
  {"id": "f6c91f9c-f4c2-58e5-9a03-70e62e719695", "slug": "patron-sarcastique", "name": "Le Patron Sarcastique", "rarity": "epique", "vibe": "ironique", "description": "« Bien sûr, prends ton vendredi. »", "hp": 92, "atk": 55, "def": 32, "spd": 86, "normalAttack": {"name": "Remarque acide", "power": 30}, "specialAttack": {"name": "Entretien annuel", "power": 65, "energyCost": 3, "effect": {"kind": "debuff", "stat": "def", "stages": 1}}, "defenseAbility": {"name": "Porte fermée", "effect": {"kind": "reflect", "percent": 30}}, "artSeed": 484844181, "imageUrl": null},
  {"id": "88f303db-b280-5c40-975e-7d768ec935cc", "slug": "raton-laveur-revolte", "name": "Raton Laveur Révolté", "rarity": "epique", "vibe": "rage", "description": "Les poubelles sont à lui. Point.", "hp": 92, "atk": 55, "def": 32, "spd": 86, "normalAttack": {"name": "Coup de patte", "power": 30}, "specialAttack": {"name": "Razzia nocturne", "power": 65, "energyCost": 3, "effect": {"kind": "pierce", "percent": 40}}, "defenseAbility": {"name": "Masque de bandit", "effect": {"kind": "dodge", "chance": 20}}, "artSeed": 1843793356, "imageUrl": null},
  {"id": "0c40d22f-d671-5ec7-afdc-d2aa3c4e41f1", "slug": "lama-zen", "name": "Lama Zen", "rarity": "epique", "vibe": "wholesome", "description": "Ne crache que des ondes positives.", "hp": 120, "atk": 37, "def": 48, "spd": 62, "normalAttack": {"name": "Mastication calme", "power": 30}, "specialAttack": {"name": "Respiration profonde", "power": 65, "energyCost": 3, "effect": {"kind": "buff", "stat": "def", "stages": 1}}, "defenseAbility": {"name": "Lâcher-prise", "effect": {"kind": "heal", "percent": 15}}, "artSeed": 577521137, "imageUrl": null},
  {"id": "0c7c1a1c-345a-5108-adc8-bf849f143403", "slug": "bug-feature", "name": "Ce Bug Est Une Feature", "rarity": "epique", "vibe": "ironique", "description": "Ce n'est pas un problème. C'est une surprise.", "hp": 98, "atk": 44, "def": 39, "spd": 88, "normalAttack": {"name": "Plantage", "power": 30}, "specialAttack": {"name": "Mise à jour forcée", "power": 65, "energyCost": 3, "effect": {"kind": "stun", "chance": 30}}, "defenseAbility": {"name": "Correctif de dernière minute", "effect": {"kind": "recharge", "amount": 1}}, "artSeed": 531519491, "imageUrl": null},
  {"id": "f110fcc9-ffa7-52d1-a06d-3bcea5567533", "slug": "hamster-turbo", "name": "Le Hamster Turbo", "rarity": "epique", "vibe": "chaos", "description": "Court depuis 3 heures. Vers nulle part.", "hp": 88, "atk": 42, "def": 40, "spd": 100, "normalAttack": {"name": "Sprint", "power": 30}, "specialAttack": {"name": "Roue infernale", "power": 65, "energyCost": 3, "effect": {"kind": "buff", "stat": "spd", "stages": 1}}, "defenseAbility": {"name": "Joues pleines", "effect": {"kind": "heal", "percent": 12}}, "artSeed": 940709171, "imageUrl": null},
  {"id": "d03c8913-b8ff-5587-8928-814517589c5b", "slug": "le-chat-qui-juge", "name": "Le Chat Qui Juge", "rarity": "legendaire", "vibe": "ironique", "description": "T'a vu. N'a rien dit. N'en pense pas moins.", "hp": 116, "atk": 48, "def": 38, "spd": 80, "normalAttack": {"name": "Regard en coin", "power": 31}, "specialAttack": {"name": "Clignement lent", "power": 75, "energyCost": 3, "effect": {"kind": "debuff", "stat": "def", "stages": 1}}, "defenseAbility": {"name": "Indifférence totale", "effect": {"kind": "reflect", "percent": 30}}, "artSeed": 377502811, "imageUrl": null},
  {"id": "ca7eac7a-5015-5e1d-ba56-46d9a0581c63", "slug": "dragon-dimanche-soir", "name": "Le Dragon du Dimanche Soir", "rarity": "legendaire", "vibe": "rage", "description": "Se réveille chaque dimanche à 19 h. Souffle l'angoisse.", "hp": 96, "atk": 57, "def": 33, "spd": 92, "normalAttack": {"name": "Souffle d'angoisse", "power": 31}, "specialAttack": {"name": "Lundi approche", "power": 70, "energyCost": 3, "effect": {"kind": "dot", "percent": 12, "turns": 2}}, "defenseAbility": {"name": "Écailles de flemme", "effect": {"kind": "reflect", "percent": 30}}, "artSeed": 136559715, "imageUrl": null},
  {"id": "e459fa96-368c-554e-a1a2-16e1de440767", "slug": "licorne-fatiguee", "name": "Licorne Fatiguée", "rarity": "legendaire", "vibe": "wholesome", "description": "Paillettes en option. Sieste obligatoire.", "hp": 126, "atk": 39, "def": 50, "spd": 64, "normalAttack": {"name": "Corne molle", "power": 31}, "specialAttack": {"name": "Arc-en-ciel réparateur", "power": 70, "energyCost": 3, "effect": {"kind": "drain", "percent": 50}}, "defenseAbility": {"name": "Sieste magique", "effect": {"kind": "heal", "percent": 18}}, "artSeed": 104415079, "imageUrl": null},
  {"id": "1fd0c60d-10e0-56d4-b3d4-617daa6f0d1e", "slug": "roi-du-cringe", "name": "Le Roi du Cringe", "rarity": "legendaire", "vibe": "cringe", "description": "Sa couronne est en papier. Il la porte au travail.", "hp": 104, "atk": 46, "def": 40, "spd": 92, "normalAttack": {"name": "Danse du roi", "power": 31}, "specialAttack": {"name": "Discours interminable", "power": 70, "energyCost": 3, "effect": {"kind": "stun", "chance": 35}}, "defenseAbility": {"name": "Assumer totalement", "effect": {"kind": "cleanse"}}, "artSeed": 1848418590, "imageUrl": null},
  {"id": "f45287e4-cbb6-55cd-9599-237ab2fdebd1", "slug": "poisson-rouge-amnesique", "name": "Poisson Rouge Amnésique", "rarity": "legendaire", "vibe": "absurde", "description": "Trois secondes de mémoire. Trois secondes de génie.", "hp": 92, "atk": 44, "def": 44, "spd": 100, "normalAttack": {"name": "Bulle", "power": 31}, "specialAttack": {"name": "Oubli total", "power": 70, "energyCost": 3, "effect": {"kind": "debuff", "stat": "atk", "stages": 1}}, "defenseAbility": {"name": "Tour du bocal", "effect": {"kind": "dodge", "chance": 30}}, "artSeed": 556697553, "imageUrl": null},
  {"id": "513ca1da-e800-585d-a602-d3b6828b6e7d", "slug": "spirale-du-scroll-infini", "name": "Spirale du Scroll Infini", "rarity": "brainrot", "vibe": "chaos", "description": "« Encore une vidéo » depuis 2019.", "hp": 116, "atk": 50, "def": 44, "spd": 80, "normalAttack": {"name": "Swipe", "power": 32}, "specialAttack": {"name": "Encore une vidéo", "power": 80, "energyCost": 4, "effect": {"kind": "drain", "percent": 40}}, "defenseAbility": {"name": "Algorithme protecteur", "effect": {"kind": "recharge", "amount": 1}}, "artSeed": 1492791933, "imageUrl": null},
  {"id": "20a066f2-66b4-5d9e-b9be-632b250d57c1", "slug": "grille-pain-interdimensionnel", "name": "Grille-Pain Interdimensionnel", "rarity": "brainrot", "vibe": "absurde", "description": "Les tartines ressortent dans une autre dimension.", "hp": 100, "atk": 60, "def": 35, "spd": 94, "normalAttack": {"name": "Tartine éjectée", "power": 32}, "specialAttack": {"name": "Portail grillé", "power": 75, "energyCost": 4, "effect": {"kind": "pierce", "percent": 50}}, "defenseAbility": {"name": "Mode décongélation", "effect": {"kind": "dodge", "chance": 30}}, "artSeed": 950272961, "imageUrl": null},
  {"id": "382f1d75-6dfe-5ea5-aa01-a6edbe02354c", "slug": "cactus-hurleur", "name": "Le Cactus Hurleur", "rarity": "brainrot", "vibe": "rage", "description": "Ne pique pas. Crie. Très fort.", "hp": 130, "atk": 40, "def": 52, "spd": 70, "normalAttack": {"name": "Épine sonore", "power": 32}, "specialAttack": {"name": "Cri du désert", "power": 75, "energyCost": 4, "effect": {"kind": "multi", "hits": 3, "percent": 40}}, "defenseAbility": {"name": "Peau épaisse", "effect": {"kind": "reflect", "percent": 40}}, "artSeed": 1654467916, "imageUrl": null},
  {"id": "81a2da99-98ec-51a2-8d83-b8fa8ea505fd", "slug": "cerveau-en-puree-cosmique", "name": "Cerveau en Purée Cosmique", "rarity": "superbrainrot", "vibe": "absurde", "description": "Pense en sons de vidéos. Parle en sous-titres.", "hp": 120, "atk": 56, "def": 42, "spd": 84, "normalAttack": {"name": "Bruit de fond", "power": 32}, "specialAttack": {"name": "Court-circuit total", "power": 82, "energyCost": 4, "effect": {"kind": "pierce", "percent": 40}}, "defenseAbility": {"name": "Bug d'affichage", "effect": {"kind": "dodge", "chance": 25}}, "artSeed": 1681357309, "imageUrl": null},
  {"id": "5f02b9b3-205d-5294-a871-ed4ad8407cf0", "slug": "l-algorithme-supreme", "name": "L'Algorithme Suprême", "rarity": "godlevel", "vibe": "chaos", "description": "Il sait ce que tu vas regarder avant toi.", "hp": 126, "atk": 56, "def": 43, "spd": 92, "normalAttack": {"name": "Notification", "power": 33}, "specialAttack": {"name": "Tendance mondiale", "power": 88, "energyCost": 4, "effect": {"kind": "buff", "stat": "atk", "stages": 1}}, "defenseAbility": {"name": "Mise à jour divine", "effect": {"kind": "heal", "percent": 15}}, "artSeed": 1959693552, "imageUrl": null},
];
